import 'package:flutter/material.dart';

import '../../../../design_system/design_system.dart';

/// "Why you're seeing him" — a privacy-safe checklist of the top reasons the
/// compatibility engine surfaced this recommendation. Reasons are generated by
/// `CompatibilityReasons.from(score)`; sensitive dimensions appear as bands
/// only (e.g. "Strong preference compatibility"), never as role specifics.
class WhyCard extends StatelessWidget {
  const WhyCard({super.key, required this.reasons});

  final List<String> reasons;

  @override
  Widget build(BuildContext context) {
    return LiquidGlassCard(
      level: GlassLevel.subtle,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.auto_awesome, size: 18, color: AppColors.accent),
              const SizedBox(width: AppSpacing.sm),
              Text('Why you\'re seeing him',
                  style: AppTypography.headingSmall),
            ],
          ),
          const SizedBox(height: AppSpacing.md),
          if (reasons.isEmpty)
            Text(
              'You\'re both new here — worth a closer look.',
              style: AppTypography.bodyMedium
                  .copyWith(color: AppColors.textSecondary),
            )
          else
            for (final r in reasons)
              Padding(
                padding: const EdgeInsets.symmetric(vertical: AppSpacing.xs),
                child: Row(
                  children: [
                    const Icon(Icons.check_circle,
                        size: 18, color: AppColors.success),
                    const SizedBox(width: AppSpacing.sm),
                    Expanded(
                      child: Text(r,
                          style: AppTypography.bodyLarge
                              .copyWith(color: AppColors.textSecondary)),
                    ),
                  ],
                ),
              ),
        ],
      ),
    );
  }
}
